[package]
name = "badger_ovba"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cfb = "0.7.3"
encoding_rs = "0.8.31"
codepage = "0.1.1"
