
pub enum CodePageBitfields {
    ANSILatin1,
    ANSILatin2,
    ANSICyrillic,
    ANSIGreek,
    ANSITurkish,
    ANSIHebrew,
    ANSIArabic,
    ANSIBaltic,
    ANSIVietnamese,
    ANSIandOEMThai,
    ANSIandOEMJapanese,
    ANSIandOEMSimplifiedChinese,
    ANSIandOEMKoreanUnifiedHangul,
    ANSIandOEMTraditionalChinese,
    ANSIandOEMKoreanJohab,
    OEMVietnamese,
    OEMModernGreek,
    OEMRussian,
    OEMNordic,
    OEMArabic,
    OEMCanadianFrench,
    OEMIcelandic,
    OEMPortuguese,
    OEMTurkish,
    OEMCyrillicRussian,
    OEMLatin2,
    OEMBaltic,
    OEMGreek,
    OEMArabicAsmo708,
    OEMArabicDos720,
    OEMMulitilingualLatin1,
    OEMUs,
}


impl CodePageBitfields {
    pub(crate) fn value(&self) -> u16 {
        match self {
            CodePageBitfields::ANSILatin1=>{1252 as u16},
            CodePageBitfields::ANSILatin2=>{1250 as u16},
            CodePageBitfields::ANSICyrillic=>{1251 as u16},
            CodePageBitfields::ANSIGreek=>{1253 as u16},
            CodePageBitfields::ANSITurkish=>{1254 as u16},
            CodePageBitfields::ANSIHebrew=>{1255 as u16},
            CodePageBitfields::ANSIArabic=>{1256 as u16},
            CodePageBitfields::ANSIBaltic=>{1257 as u16},
            CodePageBitfields::ANSIVietnamese=>{1258 as u16},
            CodePageBitfields::ANSIandOEMThai=>{874 as u16},
            CodePageBitfields::ANSIandOEMJapanese=>{932 as u16},
            CodePageBitfields::ANSIandOEMSimplifiedChinese=>{936 as u16},
            CodePageBitfields::ANSIandOEMKoreanUnifiedHangul=>{949 as u16},
            CodePageBitfields::ANSIandOEMTraditionalChinese=>{950 as u16},
            CodePageBitfields::ANSIandOEMKoreanJohab=>{1361 as u16},
            CodePageBitfields::OEMVietnamese=>{1258 as u16},
            CodePageBitfields::OEMModernGreek=>{869 as u16},
            CodePageBitfields::OEMRussian=>{866 as u16},
            CodePageBitfields::OEMNordic=>{865 as u16},
            CodePageBitfields::OEMArabic=>{864 as u16},
            CodePageBitfields::OEMCanadianFrench=>{863 as u16},
            CodePageBitfields::OEMIcelandic=>{861 as u16},
            CodePageBitfields::OEMPortuguese=>{860 as u16},
            CodePageBitfields::OEMTurkish=>{857 as u16},
            CodePageBitfields::OEMCyrillicRussian=>{855 as u16},
            CodePageBitfields::OEMLatin2=>{852 as u16},
            CodePageBitfields::OEMBaltic=>{775 as u16},
            CodePageBitfields::OEMGreek=>{737 as u16},
            CodePageBitfields::OEMArabicAsmo708=>{708 as u16},
            CodePageBitfields::OEMArabicDos720=>{720 as u16},
            CodePageBitfields::OEMMulitilingualLatin1=>{850 as u16},
            CodePageBitfields::OEMUs=>{437 as u16},
        }
    }
}