[package]
name = "badger_core"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
badger_ovba = {path = "../badger_ovba"}
structopt = "0.3.26"